# Generated by Django 4.0.6 on 2022-08-03 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booktmodel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('writer', models.CharField(max_length=100)),
                ('publication', models.CharField(max_length=150)),
                ('status', models.CharField(default='available', max_length=20)),
            ],
        ),
    ]
